#!/usr/bin/env bash

mysql --user=root --password="$MARIADB_ROOT_PASSWORD" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS $MARIADB_DATABASE;
    GRANT ALL PRIVILEGES ON \`$MARIADB_DATABASE%\`.* TO '$MARIADB_USER'@'%';
EOSQL
